[package]
name = "lol"
version = "0.1.0"
authors = ["Tobias Widlund <widlundtobias@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rodio = "0.11"

[dependencies]
rodio = "0.11"